apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: happynginxes.happy-nginx.example.com
spec:
  group: happy-nginx.example.com
  names:
    kind: HappyNginx
    listKind: HappyNginxList
    plural: happynginxes
    singular: happynginx
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
