apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: happy-nginx
  template:
    metadata:
      labels:
        name: happy-nginx
    spec:
      serviceAccountName: happy-nginx
      containers:
        - name: happy-nginx
          # Replace this with the built image name
          image: "{{ REPLACE_IMAGE }}"
          imagePullPolicy: "{{ pull_policy|default('Always') }}"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "happy-nginx"
