apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: happy-nginx
  template:
    metadata:
      labels:
        name: happy-nginx
    spec:
      serviceAccountName: happy-nginx
      containers:
        - name: happy-nginx
          image: quay.io/gfranchini/happy-nginx-ansible-operator:v0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "happy-nginx"
