kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: happy-nginx
subjects:
- kind: ServiceAccount
  name: happy-nginx
roleRef:
  kind: Role
  name: happy-nginx
  apiGroup: rbac.authorization.k8s.io
